


# payment
POST http://localhost:4000/order/kookint
Content-Type: application/json
Referer: http://localhost:4000/

{
  "personal": {"firstName": "Gilad", "lastName": "Novik", "email": "gilad@novik.ca", "phone": "0505551234"},
  "address": {"street": "אלנבי 45","city": "תל אביב","zipcode": "123456","pob": "444"},
    "items": [
        {"id": 170, "qty": 1},
        {"id": 171, "qty": 2},
        {"id": 172, "qty": 5}
    ]
}

# real payment
POST https://testicredit.rivhit.co.il/API/PaymentPageRequest.svc/GetUrl
Content-Type: application/json

{
  "GroupPrivateToken": "bb8a47ab-42e0-4b7f-ba08-72d55f2d9e41",
  "RedirectURL": "http://icredit.rivhit.co.il",
  "CustomerLastName":"david",
  "Items": [
    {
      "Quantity": 1,
      "UnitPrice": 1,
      "Description": "Item Test"
    }
    ]
}
