


# real payment
POST https://testicredit.rivhit.co.il/API/PaymentPageRequest.svc/GetUrl
Content-Type: application/json

{
  "GroupPrivateToken": "bb8a47ab-42e0-4b7f-ba08-72d55f2d9e41",
  "RedirectURL": "http://icredit.rivhit.co.il",
  "CustomerLastName":"david",
  "Items": [
    {
      "Quantity": 1,
      "UnitPrice": 10,
      "Description": "Item Test"
    }
    ]
}



# payment
POST http://localhost:4000/payment
Content-Type: application/json

{
    "items": [
        {"qty": 1, "price": 14.99, "description": "test item"}
    ]
}
