service: storystore_api
package:
  individually: true
functions:
  api:
    handler: server.api
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin


custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
